FROM php:8-apache
COPY php.ini /usr/local/etc/php/
COPY www/ /var/www/html/


LABEL "com.example.vendor"="mail@armandomarques.com"
LABEL version="1.0"
LABEL description="Apache 2.4 with php8 and adminer."
