FROM ajcm/alpine3_dev:latest

# install nodejs 8
RUN apk add --no-cache nodejs

CMD ["node"]

LABEL "com.example.vendor"="mail@armandomarques.com"
LABEL version="1.0"
LABEL description="alpine 3.x with NodeJs 18 (from apk)"

