FROM ajcm/alpine-dev:latest

# install nodejs 
RUN apk add --no-cache nodejs

CMD ["node"]

LABEL "com.example.vendor"="mail@armandomarques.com"
LABEL version="1.0"
LABEL description="Image with alpine 3.x with NodeJs (from apk)."

